### ISSUE TITLE
Rollapp that start with "Z" is not showing on Portal

### ISSUE THREAD

**Issue by nmluthfi** [dymensionxyz/rollapp-registry#2022]
Hi Dymension.

Since today, any portal that start with the letter "Z" is not found on Portal. I've seen 2 Rollapp portals that experienced the issue

1. https://portal.dymension.xyz/rollapp/zozak_8767363-1
2. https://portal.dymension.xyz/rollapp/zuperchain_6991015-1 (mine)

Suppose you take a look at my rollapp, the chain itself working just fine. Sequencer, relayer, and Avail have no issues.

**Comment by AkifhanIlgaz** [comment]
It may be about something else. I see rollapps that start with "z" on the portal

**Comment by nmluthfi** [comment]
I don' think so ser. Our chain is fully functional. Block heigh is increasing, relayer, and sequencer work as usual.

**Comment by nmluthfi** [comment]
> It may be about something else. I see rollapps that start with "z" on the portal


I don' think so ser. Our chain is fully functional. Block heigh is increasing, relayer, and sequencer work as usual.

**Comment by nmluthfi** [comment]
another rollapp starting with "Z" has gone https://portal.dymension.xyz/rollapp/zoro_5667677-1. 

ccing team for better visibility: @ItayLevyOfficial @yishay-dym

**Comment by mohammadyogi** [comment]
Today my rollapp has gone from the portal, my portal name started letter from Y : https://portal.dymension.xyz/rollapp/yogicz_5790483-1

**Comment by vodov93** [comment]
I also experienced the same problem, my rollapp : 
https://portal.dymension.xyz/rollapp/zaraki_4232707-1

**Comment by AkifhanIlgaz** [comment]
I can see my rollapp on the portal now. Did the issue is solved for all of you ? https://portal.dymension.xyz/rollapp/zozak_8767363-1

**Comment by nmluthfi** [comment]
> I can see my rollapp on the portal now. Did the issue is solved for all of you ? https://portal.dymension.xyz/rollapp/zozak_8767363-1

Yes, all rollapp is now showing on Portal. Problem closed.
